= CF Workshop Continuous Delivery Lab

== Intro

This lab will guide you through building a *BASIC* continuous delivery pipeline using Jenkins and Cloud Foundry.

== Initial Setup

. Fork the Spring-Music repository. If you do not have a github account, you can skip this step and use my repository.

`https://github.com/cloudfoundry-samples/spring-music.git`
 
. Edit the manifest.yml at the root of the forked spring-music repository. Change the *host* from ${random-word} to your initials. Jenkins does not like the special characters in the host field and will give an error.
  
. Login to your Jenkins instance at https://jenkins-0.system.pcf.mts.inbcu.com/ with the same username and password that you use for CloudFoundry.


== Create the Build Job

. Click *New Item*, give it the name *spring-music* and select ``Build a free-style software project.'' Then click +OK+.

== Configure Git

. Under *Source Code Management*, select *Git*, and supply your repository URL (e.g. `https://github.com/<YOUR_GIT_USERNAME>/spring-music`). Leave credentials as *none*.

. On "Build Triggers", select "Build when a change is pushed to GitHub", and "POLL SCM"
+
POLL SCM Settings to check for changes on an interval (every minute in this case):
+
[source, bash]
----------------
*/1 * * * *
----------------

== Configure Gradle Build

. Select *Add Build Step* and then *Invoke Gradle Script*.

. Select *Use Grade Wrapper*.

. Check both *Make gradlew executable* and *From Root Build Script Directory*.

. In switches, enter `-Pbuildversion=$BUILD_NUMBER`
+
If your Jenkins Instance is configured for a Proxy (eg. 100.115.73.81:443) add switch:

[source, bash]
----------------
-Dhttp.proxyHost=100.115.73.81 -Dhttp.proxyPort=443 -Dhttps.proxyHost=100.115.73.81 -Dhttps.proxyPort=443
----------------

. In tasks, enter `clean assemble`.

. In build file, enter `build.gradle`.

. Check _Force GRADLE_USER_HOME_ to use workspace.

== Execute Shell
[source,bash]
----
DEPLOYED_VERSION_CMD=$(CF_COLOR=false cf apps | grep 'mapUS.' | cut -d" " -f1)
export BUILD_VERSION="1.2"
export DEPLOYED_VERSION_CMD
echo DEPLOYED_VERSION_CMD
export ROUTE_VERSION="default"
echo "Deployed Version: $DEPLOYED_VERSION"
echo "Route Version: $ROUTE_VERSION"

# Save your api target in variable API
export API=https://api.system.pcf.mts.inbcu.com

# Set current target api to API
cf api --skip-ssl-validation $API

# Use your credentials here to login
cf login -u username -p password -o org -s space

# Create an instance of the mysql service
cf create-service p-mysql 100mb-dev spring-music-db

# Create/Update the spring-music app using the versioned manifest.yml, but dont start
cf push spring-music -f manifest.yml --no-start

# Bind the application to the service instance
cf bind-service spring-music spring-music-db

# Start the application
cf start spring-music
----


== Execute Build Job

. Select *Build Now*.

. Select the build in *Build History*, then select *Console Output*.

. Jenkins should build and push the app, then you can click the link at the bottom to see the running app.


== Labs
 * Lab 1 - From Zero to Pushing Your First Application
 ** link:../lab1/lab.adoc[**Java** Application]
 ** link:../lab1/lab-ruby.adoc[**Ruby** Application]
 * link:../lab2/lab.adoc[Lab 2 - Binding to Cloud Foundry Services]
 * link:../lab3/lab.adoc[Lab 3 - Operating Your Application]
 * link:../lab4/lab.adoc[Lab 4 - Monitoring Your Application]
 * link:../lab5/continuous-delivery-lab.adoc[Advanced Lab - Jenkins Integration]
